ALTER TABLE users ADD COLUMN tg_user_id BIGINT NULL;
ALTER TABLE users ADD COLUMN tg_username VARCHAR(100) NULL;
ALTER TABLE users ADD COLUMN tg_linked_at TIMESTAMP NULL;
ALTER TABLE users ADD UNIQUE KEY uq_users_tg (tg_user_id);

CREATE TABLE IF NOT EXISTS tg_link_codes (
    code VARCHAR(12) PRIMARY KEY,
    user_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tlc_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS player_avatars (
    id INT AUTO_INCREMENT PRIMARY KEY,
    player_id INT NOT NULL,
    file VARCHAR(255) NOT NULL,
    thumb VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pa_player FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE tournaments ADD COLUMN logo VARCHAR(255) NULL

